### Gets all orders
GET {{hostUrl}}/api/orders
Authorization: Bearer {{bearerToken}}
Accept: application/json

### Gets top 1 orders
GET {{hostUrl}}/api/orders?top=1
Authorization: Bearer {{bearerToken}}
Accept: application/json

### Gets next 1 orders with continuation token
GET {{hostUrl}}/api/orders?top=1
Authorization: Bearer {{bearerToken}}
Accept: application/json
X-Continuation-Token: T3JkZXJz MDA2YmZmNzUtYjY1Zi00YjkyLTg5NGYtZmJiNDExMDliMjNi

### Adds order
POST {{hostUrl}}/api/orders
Authorization: Bearer {{bearerToken}}
Content-Type: application/json
Accept: application/json

{
  "orderLines": [
      { "bookId": 29, "quantity": 10 },
      { "bookId": 30, "quantity": 15 },
      { "bookId": 31, "quantity": 20 }
  ]
}